vich_uploader:
    db_driver: orm

    mappings:
        ticket_message_attachment:
            uri_prefix:         /attachment
            upload_destination: "%kernel.project_dir%/../var/uploads/attachment/"
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
