imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['bootstrap_3_layout.html.twig']

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver:              orm
    firewall_name:          oauth
    user_class:             AppBundle\Entity\User
    use_listener:           true
    use_username_form_type: true
    from_email:
        address:        "%from_email_address%"
        sender_name:    "%from_email_name%"

hackzilla_ticket:
    user_class:             AppBundle\Entity\User
    ticket_class:           AppBundle\Entity\Ticket
    message_class:          AppBundle\Entity\TicketMessage
    event_manager:         'hackzilla_ticket.event_manager.symfony'
    storage_manager:       'hackzilla_ticket.storage_manager.doctrine_orm'
    translate_manager:     'hackzilla_ticket.translate_manager.symfony'
    user_manager:          'hackzilla_ticket.user_manager.symfony'
    features:
        - 'attachment'
    pagination:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        items_per_page: 10

vich_uploader:
    db_driver: mongodb

white_october_pagerfanta:
    default_view: twitter_bootstrap3

#
#    mappings:
#        ticket_message_attachment:
#            uri_prefix:         /attachment
#            upload_destination: %kernel.root_dir%/../var/uploads/attachment/
